### ISSUE TITLE
state of git**lab** mirror

### ISSUE THREAD

**Issue by ghost** [Aardwolf-Social/aardwolf-website#1]
its currently missing, but blog-post about it still exist:
https://github.com/Aardwolf-Social/aardwolf-website/blob/master/_posts/2018-02-06-gitlab.md
( https://aardwolf.social/news/2018/02/06/gitlab )

just a small confusing inconsistency

**Comment by BanjoFox** [comment]
I will fix that now.

**Comment by BanjoFox** [comment]
What is missing exactly?
The blog post refers to: https://gitlab.com/AndMyAxe/aardwolf which is a valid URL

In fact the GitLab repo was updated 6 minutes ago as of this post.

**Comment by ghost** [comment]
is that repo private?
![Screenshot_2019-12-14 Sign in](https://user-images.githubusercontent.com/39516339/70842362-fe285980-1e22-11ea-9050-7d8e307e20b3.png)
![Screenshot from 2019-12-14 03-34-14](https://user-images.githubusercontent.com/39516339/70842363-01bbe080-1e23-11ea-935e-225a57578a7f.png)

**Comment by BanjoFox** [comment]
Yeah.... that would make sense >.<!
It looks like AndMyAxe made all of them Private.

Pulling a new copy to a group that I actually own.  Appologies

https://gitlab.com/BanjoFox/aardwolf
